<#
    Registers the recordings viewer as a hidden background web server that
    starts at logon, so the recordings can be browsed from another PC without
    anyone opening a terminal on this machine.

    The server binds to localhost unless "viewerBindAll": true is set in
    config.json; when it does bind to all interfaces, this script also opens
    the chosen port on the Windows Firewall for the private network.
#>
param(
    [string]$TaskName = 'ScreenActivityViewer'
)

$ErrorActionPreference = 'Stop'
$root  = Split-Path -Parent $PSScriptRoot
$entry = Join-Path $root 'src\server.js'

$node = (Get-Command node.exe -ErrorAction SilentlyContinue).Source
if (-not $node) { throw 'node.exe was not found on PATH. Install Node.js first.' }

$cfg  = Get-Content (Join-Path $root 'config.json') -Raw | ConvertFrom-Json
$port = if ($cfg.viewerPort) { [int]$cfg.viewerPort } else { 8088 }
$scheme = if ($cfg.viewerHttps) { 'https' } else { 'http' }

# Make sure a certificate exists when HTTPS is on, otherwise the server exits.
if ($cfg.viewerHttps) {
    $hasPem = $cfg.viewerCertFile -and $cfg.viewerKeyFile -and
              (Test-Path (Join-Path $root $cfg.viewerCertFile)) -and
              (Test-Path (Join-Path $root $cfg.viewerKeyFile))
    $hasPfx = Test-Path (Join-Path $root 'certs\viewer.pfx')
    if (-not $hasPem -and -not $hasPfx) {
        Write-Host 'HTTPS is enabled but no certificate was found - generating one ...'
        & (Join-Path $PSScriptRoot 'setup-cert.ps1')
    }
}

# Hidden launcher, same approach as the recorder: wscript runs node with no window.
$vbs = Join-Path $root 'launch-viewer-hidden.vbs'
@"
' Generated by scripts\install-viewer.ps1 - starts the viewer with no window.
Set shell = CreateObject("WScript.Shell")
shell.CurrentDirectory = "$root"
shell.Run """$node"" ""$entry""", 0, False
"@ | Out-File -FilePath $vbs -Encoding Unicode -Force

$action  = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument """$vbs"" //B"
$trigger = New-ScheduledTaskTrigger -AtLogOn -User "$env:USERDOMAIN\$env:USERNAME"
$trigger.Delay = 'PT25S'

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable `
    -MultipleInstances IgnoreNew `
    -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1) `
    -ExecutionTimeLimit (New-TimeSpan -Seconds 0)
$settings.DisallowStartIfOnBatteries = $false
$settings.StopIfGoingOnBatteries = $false

$principal = New-ScheduledTaskPrincipal `
    -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType Interactive -RunLevel Limited

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
    -Settings $settings -Principal $principal `
    -Description 'Serves recorded screen videos over HTTP for browser viewing.' -Force | Out-Null

Write-Host "Registered scheduled task '$TaskName' for $env:USERDOMAIN\$env:USERNAME."

if ($cfg.viewerBindAll) {
    $ruleName = "ScreenActivityViewer TCP $port"
    $isAdmin = ([Security.Principal.WindowsPrincipal] `
        [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
        [Security.Principal.WindowsBuiltInRole]::Administrator)

    # Refresh any old rule so a changed port takes effect.
    Get-NetFirewallRule -DisplayName 'ScreenActivityViewer TCP*' -ErrorAction SilentlyContinue |
        Remove-NetFirewallRule -ErrorAction SilentlyContinue

    if ($isAdmin) {
        # All profiles, not just Private: the active network may be Public or
        # Domain, and a Private-only rule would silently not apply.
        New-NetFirewallRule -DisplayName $ruleName -Direction Inbound -Action Allow `
            -Protocol TCP -LocalPort $port -Profile Any | Out-Null
        Write-Host "Opened TCP $port on the Windows Firewall (all profiles)."
    } else {
        Write-Warning "Adding a firewall rule needs administrator rights - skipped."
        Write-Host "Other PCs will be blocked until TCP $port is allowed. Run this in an"
        Write-Host "elevated PowerShell (Run as administrator):"
        Write-Host ""
        Write-Host "  New-NetFirewallRule -DisplayName '$ruleName' -Direction Inbound -Action Allow -Protocol TCP -LocalPort $port -Profile Any"
        Write-Host ""
    }
} else {
    Write-Host 'Viewer is bound to localhost. To reach it from another PC, set "viewerBindAll": true in config.json and re-run this script.'
}

Write-Host ''
Write-Host 'Starting it now ...'
Start-ScheduledTask -TaskName $TaskName
Start-Sleep -Seconds 3

$ips = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
    Where-Object { $_.IPAddress -notlike '169.*' -and $_.IPAddress -ne '127.0.0.1' } |
    Select-Object -ExpandProperty IPAddress
Write-Host ''
Write-Host 'Open in a browser:'
Write-Host "  On this PC:      ${scheme}://localhost:$port"
if ($cfg.viewerBindAll -and $ips) {
    foreach ($ip in $ips) { Write-Host "  From another PC: ${scheme}://${ip}:$port" }
}
