<#
    Registers the recorder as a hidden background process that starts
    automatically every time this user logs on.

    A logon Scheduled Task is used rather than a Windows Service on purpose:
    screen capture (gdigrab) needs an interactive desktop, which session-0
    services do not have.
#>
param(
    [string]$TaskName = 'ScreenActivityRecorder'
)

$ErrorActionPreference = 'Stop'

$taskName = $TaskName
$root     = Split-Path -Parent $PSScriptRoot
$entry    = Join-Path $root 'src\index.js'

$node = (Get-Command node.exe -ErrorAction SilentlyContinue).Source
if (-not $node) { throw 'node.exe was not found on PATH. Install Node.js first.' }

# wscript + a tiny VBS wrapper keeps the console window from flashing at logon.
$vbs = Join-Path $root 'launch-hidden.vbs'
@"
' Generated by scripts\install-autostart.ps1 - starts the recorder with no window.
Set shell = CreateObject("WScript.Shell")
shell.CurrentDirectory = "$root"
shell.Run """$node"" ""$entry""", 0, False
"@ | Out-File -FilePath $vbs -Encoding Unicode -Force

$action = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument """$vbs"" //B"

$trigger = New-ScheduledTaskTrigger -AtLogOn -User "$env:USERDOMAIN\$env:USERNAME"
$trigger.Delay = 'PT20S'   # let the desktop finish loading first

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -MultipleInstances IgnoreNew `
    -RestartCount 3 `
    -RestartInterval (New-TimeSpan -Minutes 1) `
    -ExecutionTimeLimit (New-TimeSpan -Seconds 0)
$settings.DisallowStartIfOnBatteries = $false
$settings.StopIfGoingOnBatteries = $false

$principal = New-ScheduledTaskPrincipal `
    -UserId "$env:USERDOMAIN\$env:USERNAME" `
    -LogonType Interactive `
    -RunLevel Limited

Register-ScheduledTask `
    -TaskName $taskName `
    -Action $action `
    -Trigger $trigger `
    -Settings $settings `
    -Principal $principal `
    -Description 'Records the screen in 3-hour H.264 segments while the user is active.' `
    -Force | Out-Null

Write-Host "Registered scheduled task '$taskName' for $env:USERDOMAIN\$env:USERNAME."
Write-Host "Launcher: $vbs"
Write-Host ''
Write-Host 'Starting it now ...'
Start-ScheduledTask -TaskName $taskName
Start-Sleep -Seconds 3
Get-ScheduledTask -TaskName $taskName |
    Get-ScheduledTaskInfo |
    Select-Object TaskName, LastRunTime, LastTaskResult
